# WhatATheme
markdown: kramdown

# URL of the Site
url: 'https://invoany.github.io'
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Invoany BigData Projects 
# Description of the Site
description: A Personal Website containing some of my most relevant projects in BigData, Python and Data Visualization.
# URL of Image of the Site
site-image: /Invoany.Github.io/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: jorgenunes88@gmail.com
facebook_username: 
twitter_username: Invoany
instagram_username: Invoany
linkedin_username: Invoany
github_username:  Invoany
youtube_channel_id:
reddit_username: 
behance_username: 
dribbble_username: 
spotify_username: 

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: invoany-github-io

# Name of the Author
author-name: Invoany
# URL for the Image of the Author
author-image: \assets\images\posts\web-scraping\Jorge formal.jpg
# 60 Words About the Author
author-about: Hi! I'm Jorge! I just Love Data, I'm always looking to show unpredictable results and outcomes, eager to create autonomous programs, wining time for Creation!
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/Invoany

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
